name: Set Cloudflare Pages Compatibility Flags

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  set-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run flag setter
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGES_PROJECT: ${{ secrets.CF_PAGES_PROJECT }}
          CF_COMPAT_FLAGS: nodejs_compat
        run: |
          node scripts/set-cf-compat-flags.mjs

