name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run API tests
        run: npm run test:api
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}

      - name: Run integration tests
        run: npm run test:integration
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}

      - name: Run code execution tests
        run: npm run test:code
        env:
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}

      - name: Run all tests
        run: npm run test:all
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          E2B_API_KEY: ${{ secrets.E2B_API_KEY }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7